server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/customer
    username: root
    password: kab0411
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

cloud:
  config:
    uri: http://config-server:8888
    fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/